update

diff --git a/.github/workflows/bor-release.yml b/.github/workflows/bor-release.yml
--- a/.github/workflows/bor-release.yml
+++ b/.github/workflows/bor-release.yml
@@ -29,10 +29,10 @@ jobs:
           
           echo "UPSTREAM_TAG=$upstream_tag" >> "$GITHUB_OUTPUT"
           echo "ORIGIN_TAG=$origin_tag" >> "$GITHUB_OUTPUT"
-          # fail if any of the tags is null or if the tags are the same
-          [[ -z $upstream_tag || -z $origin_tag || $upstream_tag == $origin_tag ]] && { echo "Check if tags are not null or not the same"; exit 1; }
           echo "Upstream: $upstream_tag"
           echo "Origin: $origin_tag"
+          # fail if any of the tags is null or if the tags are the same
+          [[ -z $upstream_tag || -z $origin_tag || $upstream_tag == $origin_tag ]] && { echo "Check if tags are not null or not the same"; exit 1; }
 
 
       - name: Print tags
